server.port=8080
spring.application.name=observacao
spring.main.banner-mode=off
logging.level.root=WARN

spring.data.mongodb.uri=mongodb://localhost:27017/observacao

springdoc.swagger-ui.path=/swagger-ui.html
